FROM python:3.11-slim

WORKDIR /app

COPY requirements-train.txt .
RUN pip install --no-cache-dir -r requirements-train.txt

COPY config/ config/
COPY src/ src/

CMD ["python", "-m", "src.pipeline.run_pipeline"]
